fix over array of objects not finding class
cedricziel/mattermost-php pull request #146
Opened 2024-06-05 13:14 UTC by schojnicki-sembot

2024-06-06 21:14 UTC, cedricziel commented
Thank you, @schojnicki-sembot !

Can you explain what this change does?

2024-06-11 17:21 UTC, slnw commented
should be `str_replace` in case package isn't being used in Laravel.

2024-06-11 17:26 UTC, slnw requested changes

2024-06-11 17:26 UTC, slnw commented on src/Client/HttpClientTrait.php
> +                Str::replace('[]', '', $map[$responseCode]);
$map[$responseCode] = str_replace('[]', '', $map[$responseCode]);

2024-06-11 17:27 UTC, slnw commented
> problem class[] cannot be found therefore i wanted to strip the [] from class name so it will create an array of objects in given class

should be `$map[$responseCode] = str_replace('[]', '', $map[$responseCode]);`

2024-06-11 18:50 UTC, slnw commented
@cedricziel pls merge

2024-06-15 07:28 UTC, merged